### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by GuiSim** [coveo/spillway#16]
Hi guys!

Do you think Spillway is ready to publish to Maven Central? If so, could you please do it?

**Comment by Sytten** [comment]
We are still working on some stuff.
1. Limit Overrides (in PR)
2. Batch of requests to avoid a request to redis each time a query arrives

**Comment by malaporte** [comment]
We could still publish a version, maybe a 0.x one? Don't wait until it's perfect :)

**Comment by Sytten** [comment]
Its published in our own maven server as a RC1

**Comment by Sytten** [comment]
RC2 available on our server

**Comment by Sytten** [comment]
After #19 is merged, I will publish a V1 to maven central.

**Comment by Sytten** [comment]
Published!
