### ISSUE TITLE
Change formatting

### ISSUE THREAD

**Issue by Sytten** [coveo/spillway#30]
I suggest to change the formatting to the one we use in Cloud V2...
- tab = 4 spaces
- no strange line return after (
- no strange line return after operator
- etc

**Comment by malaporte** [comment]
This project uses the formatting from the Google formatter, which is not configurable (a good thing). All our Java OSS projects use this, and I think we should keep it this way. It makes it easier for external contributors, avoids fights over personal preferences, etc.

**Comment by Sytten** [comment]
Ho, nice to known. Issue done then...
