### ISSUE TITLE
Any news?

### ISSUE THREAD

**Issue by Sytten** [coveo/spillway#34]
Any news about the project?
Does it behave well?
Did you found bugs?

**Comment by malaporte** [comment]
Hello Emile!

It's been running in production for a few months now, monitoring and throttling incoming traffic, queries, etc. I see in our metrics that it regularly throttles requests when someones decides to load test our endpoints, etc. So I guess it's working pretty well for our present use case.

The project clearly is still active, but I can't say that I'm aware of any issue that we'd need to address at the moment. Of course there is always room for improvement - for example, it can be a bit unforgiving when enforcing lower quotas. That's not a big problem for larger customers (their limits are quite high anyway), but now that we offer free & low cost versions this might become a problem. I'd be cool to add some better handling for bursts.

@vseguin feel free to chime in 😁

**Comment by vseguin** [comment]
Aaaaa, coincidence! It's been working pretty well, but we would like to improve it a bit. Especially, improve read capacity of your current state for instance. We planned to work on that in the next few weeks, and will gladly accept reviews on an upcoming pill request 😁

**Comment by Sytten** [comment]
Ha cool! I will follow the work here. Tell the person working on it to continue the v2 branch, he can also look at the sliding window I coded a while ago. Would be nice to publish a real V2 on mvn central when the changes are done!  I have some time before my internship starts (if I can get my danish visa :p), so I might work on it in my spare time.

**Comment by Sytten** [comment]
I reviewed the PR, it's great, but he started from branch V1 :/
Anyway I'm closing the issue...
