### ISSUE TITLE
Documentation for AWS integration

### ISSUE THREAD

**Issue by cirrus-up-cloud** [coveo/spillway#45]
Hi,

I wrote a post describing how to integrate Spillway with AWS ElastiCache.
If you find useful, please link it in the library documentation.
Link to the article: https://tinyurl.com/ydxtnv7k

**Comment by Sytten** [comment]
Nice thanks a lot! I don't have write access to the repo anymore, but someone from coveo can add it :)

**Comment by malaporte** [comment]
Thanks! I added a link to the README.md file
