### ISSUE TITLE
Allow asynchronous backend operations 

### ISSUE THREAD

**Issue by GuiSim** [coveo/spillway#8]
Use a in-memory variant, batch increment periodically to the backend.

Applications should have the choice, if they don't need the ultra-precise counter, they should be able to wrap the storage in a "good enough" estimate that doesn't negatively impact performance on every call to `call`.

**Comment by GuiSim** [comment]
@malaporte Do you think that having a setting to determine which % of requests we actually send to the backend would be good enough? And then you multiply the counter by the %.

Say you only send 20% of actual `call()` to the backend and you multiply the `cost` by 5 (which is 100%/20%). Once a limit is exceeded, you fail every call until the expiration is reached and then you start again.

This seems like a very simple thing to code and could perhaps meet the requirements. I'd like your thoughts.

**Comment by malaporte** [comment]
But why not batch the writes and flush them every X seconds? Then you'd get an exact count at that moment at least. And you'd never exceed the threshold for more than X seconds (at worst).

**Comment by GuiSim** [comment]
@malaporte Because it is quite a bit more complex. I kind of wish we could avoid asynchronous cron jobs.

Also, the synchronization of the memory VS actual storage might be more complex than it appears.
I'll keep looking into it.
